In [1]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
arr=np.arange(6)
arr_2d=arr.reshape(2,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]]


In [4]:
import numpy as np
arr=np.array([[1,2],[2,3],[3,4]], dtype=np.uint16)
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.itemsize)

Shape:  (3, 2)
Dimension:  2
Size:  2


In [12]:
import numpy as np
arr=np.ones((3,3),dtype=bool)
print(arr)
ar=np.zeros((2,2),dtype=bool)
print(ar)
a_r=np.zeros((2,4))
print(a_r)
aR=np.ones(5)
print(aR)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False]
 [False False]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]


In [9]:
import numpy as np
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [14]:
import numpy as np
arr=np.linspace(5,50,10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [19]:
import numpy as np
py_list=[1,2,3,4,5]
arr=np.array(py_list)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [23]:
import numpy as np
arr=np.array([2,5,10,6,12,7,1,8,9])
print(arr.nbytes)

72


In [27]:
import numpy as np
arr=np.arange(10)
#reversed_arr=np.flip(arr)
reversed_arr=arr[::-1]
print(reversed_arr)

[9 8 7 6 5 4 3 2 1 0]


In [30]:
arr=np.arange(10)
slice=arr[2:7:2]
print(slice)
print(arr[2], arr[4], arr[6])

[2 4 6]
2 4 6


In [31]:
id=np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
arr=np.arange(1,17).reshape(4,4)
print("Re-Shaped: \n", arr)

row1=arr[0,:]
print("Row 1st: ", row1)

lastcol=arr[::,-1]
print("Last Col: ", lastcol)

somecol=arr[::,-2]
print("some Col: ", somecol)

rowsome=arr[2,:]
print("Some Row: ", rowsome)

Re-Shaped: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row 1st:  [1 2 3 4]
Last Col:  [ 4  8 12 16]
some Col:  [ 3  7 11 15]
Some Row:  [ 9 10 11 12]


In [22]:
import numpy as np
arr=np.array([2,5,10,6,12,7,1,8,9])
print(arr[(arr>=5)&(arr<=10)])

[ 5 10  6  7  8  9]


In [43]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print(mat.max())
print(mat.min())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
